// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

// The request message containing the user's name.
type User struct {
	ID                   uint64               `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ActivatedAt          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=activatedAt,proto3" json:"activatedAt,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string               `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Sex                  string               `protobuf:"bytes,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Score                uint64               `protobuf:"varint,8,opt,name=Score,proto3" json:"Score,omitempty"`
	Signature            string               `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	AvatarURL            string               `protobuf:"bytes,10,opt,name=avatarURL,proto3" json:"avatarURL,omitempty"`
	Role                 uint32               `protobuf:"varint,11,opt,name=Role,proto3" json:"Role,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status               int32                `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d48ecde398e88f1c, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetActivatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ActivatedAt
	}
	return nil
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *User) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *User) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *User) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

func (m *User) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type SignupReq struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Sex                  string   `protobuf:"bytes,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Score                uint64   `protobuf:"varint,8,opt,name=Score,proto3" json:"Score,omitempty"`
	Signature            string   `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupReq) Reset()         { *m = SignupReq{} }
func (m *SignupReq) String() string { return proto.CompactTextString(m) }
func (*SignupReq) ProtoMessage()    {}
func (*SignupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d48ecde398e88f1c, []int{1}
}
func (m *SignupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupReq.Unmarshal(m, b)
}
func (m *SignupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupReq.Marshal(b, m, deterministic)
}
func (dst *SignupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupReq.Merge(dst, src)
}
func (m *SignupReq) XXX_Size() int {
	return xxx_messageInfo_SignupReq.Size(m)
}
func (m *SignupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignupReq proto.InternalMessageInfo

func (m *SignupReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignupReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignupReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignupReq) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *SignupReq) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *SignupReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type LoginReq struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	LuosimaoRes          string   `protobuf:"bytes,3,opt,name=luosimaoRes,proto3" json:"luosimaoRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d48ecde398e88f1c, []int{2}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetLuosimaoRes() string {
	if m != nil {
		return m.LuosimaoRes
	}
	return ""
}

type LoginRep struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRep) Reset()         { *m = LoginRep{} }
func (m *LoginRep) String() string { return proto.CompactTextString(m) }
func (*LoginRep) ProtoMessage()    {}
func (*LoginRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d48ecde398e88f1c, []int{3}
}
func (m *LoginRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRep.Unmarshal(m, b)
}
func (m *LoginRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRep.Marshal(b, m, deterministic)
}
func (dst *LoginRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRep.Merge(dst, src)
}
func (m *LoginRep) XXX_Size() int {
	return xxx_messageInfo_LoginRep.Size(m)
}
func (m *LoginRep) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRep.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRep proto.InternalMessageInfo

func (m *LoginRep) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRep) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginRep) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LogoutReq struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d48ecde398e88f1c, []int{4}
}
func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (dst *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(dst, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type LogoutRep struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRep) Reset()         { *m = LogoutRep{} }
func (m *LogoutRep) String() string { return proto.CompactTextString(m) }
func (*LogoutRep) ProtoMessage()    {}
func (*LogoutRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d48ecde398e88f1c, []int{5}
}
func (m *LogoutRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRep.Unmarshal(m, b)
}
func (m *LogoutRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRep.Marshal(b, m, deterministic)
}
func (dst *LogoutRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRep.Merge(dst, src)
}
func (m *LogoutRep) XXX_Size() int {
	return xxx_messageInfo_LogoutRep.Size(m)
}
func (m *LogoutRep) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRep.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRep proto.InternalMessageInfo

func (m *LogoutRep) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*SignupReq)(nil), "protobuf.SignupReq")
	proto.RegisterType((*LoginReq)(nil), "protobuf.LoginReq")
	proto.RegisterType((*LoginRep)(nil), "protobuf.LoginRep")
	proto.RegisterType((*LogoutReq)(nil), "protobuf.LogoutReq")
	proto.RegisterType((*LogoutRep)(nil), "protobuf.LogoutRep")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_d48ecde398e88f1c) }

var fileDescriptor_user_d48ecde398e88f1c = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x52, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0xdd, 0xa4, 0x49, 0xd8, 0x4c, 0x68, 0x85, 0x4c, 0x85, 0xac, 0x00, 0x22, 0xca, 0x29, 0xa7,
	0xad, 0xd8, 0x72, 0xe0, 0xc0, 0x05, 0xa9, 0x97, 0x4a, 0x7b, 0x40, 0x5e, 0xca, 0x11, 0xc9, 0xdd,
	0x0e, 0x21, 0x62, 0x13, 0x1b, 0xdb, 0x59, 0xf8, 0x27, 0xc4, 0x0f, 0x72, 0x42, 0xb6, 0x37, 0xc9,
	0x52, 0x8a, 0xb8, 0xf6, 0x94, 0x79, 0x6f, 0xc6, 0x6f, 0xe6, 0x4d, 0x06, 0xa0, 0xd7, 0xa8, 0x16,
	0x52, 0x09, 0x23, 0xc8, 0xdc, 0x7d, 0xae, 0xfb, 0x4f, 0xf9, 0x8b, 0x5a, 0x88, 0x7a, 0x8b, 0x67,
	0x03, 0x71, 0x66, 0x9a, 0x16, 0xb5, 0xe1, 0xad, 0xf4, 0xa5, 0xe5, 0xaf, 0x10, 0xa2, 0x2b, 0x8d,
	0x8a, 0x9c, 0x40, 0x78, 0x79, 0x41, 0x83, 0x22, 0xa8, 0x22, 0x16, 0x5e, 0x5e, 0x10, 0x02, 0x51,
	0xc7, 0x5b, 0xa4, 0x61, 0x11, 0x54, 0x29, 0x73, 0x31, 0x79, 0x03, 0x19, 0xdf, 0x98, 0x66, 0xc7,
	0x0d, 0xde, 0xbc, 0x35, 0xf4, 0xa8, 0x08, 0xaa, 0x6c, 0x99, 0x2f, 0x7c, 0x8f, 0xc5, 0xd0, 0x63,
	0xf1, 0x7e, 0xe8, 0xc1, 0x0e, 0xcb, 0x49, 0x0e, 0x73, 0xc9, 0xb5, 0xfe, 0x26, 0xd4, 0x0d, 0x8d,
	0x9c, 0xea, 0x88, 0xc9, 0x29, 0xc4, 0xd8, 0xf2, 0x66, 0x4b, 0x63, 0x97, 0xf0, 0xc0, 0xb2, 0xf2,
	0xb3, 0xe8, 0x90, 0x26, 0x9e, 0x75, 0x80, 0x3c, 0x82, 0x23, 0x8d, 0xdf, 0xe9, 0x03, 0xc7, 0xd9,
	0xd0, 0xd6, 0xad, 0x37, 0x42, 0x21, 0x9d, 0xbb, 0xf1, 0x3d, 0x20, 0xcf, 0x20, 0xd5, 0x4d, 0xdd,
	0x71, 0xd3, 0x2b, 0xa4, 0xa9, 0xab, 0x9e, 0x08, 0x9b, 0xe5, 0x3b, 0x6e, 0xb8, 0xba, 0x62, 0x2b,
	0x0a, 0x3e, 0x3b, 0x12, 0xd6, 0x3d, 0x13, 0x5b, 0xa4, 0x59, 0x11, 0x54, 0xc7, 0xcc, 0xc5, 0xe4,
	0x35, 0xa4, 0x1b, 0x85, 0x7b, 0xef, 0x0f, 0xff, 0xeb, 0x7d, 0x2a, 0x26, 0x4f, 0x20, 0xd1, 0x86,
	0x9b, 0x5e, 0xd3, 0xe3, 0x22, 0xa8, 0x62, 0xb6, 0x47, 0xe5, 0xcf, 0x00, 0xd2, 0x75, 0x53, 0x77,
	0xbd, 0x64, 0xf8, 0xf5, 0xce, 0x8d, 0xdf, 0xab, 0x9d, 0x95, 0x1f, 0x61, 0xbe, 0x12, 0x75, 0xd3,
	0xd9, 0x69, 0x4f, 0x21, 0x6e, 0x3a, 0xd9, 0x1b, 0x77, 0x32, 0x29, 0xf3, 0xe0, 0x8f, 0x79, 0xc3,
	0x5b, 0xf3, 0x16, 0x90, 0x6d, 0x7b, 0xa1, 0x9b, 0x96, 0x0b, 0x86, 0xda, 0x5d, 0x4f, 0xca, 0x0e,
	0xa9, 0xf2, 0xc3, 0xa8, 0x2f, 0xad, 0xbe, 0x11, 0x5f, 0xb0, 0x1b, 0xf4, 0x1d, 0x20, 0x25, 0x44,
	0xf6, 0xce, 0x9d, 0x76, 0xb6, 0x3c, 0x99, 0xf6, 0x6e, 0x6f, 0x98, 0xb9, 0x9c, 0xf5, 0xda, 0xea,
	0x7a, 0xaf, 0x6f, 0xc3, 0xf2, 0x29, 0xa4, 0x2b, 0x51, 0x8b, 0xde, 0xd8, 0xc1, 0x6f, 0x1d, 0x7a,
	0xf9, 0x7c, 0x4a, 0xca, 0xe1, 0x6d, 0x30, 0xbe, 0x5d, 0xfe, 0x08, 0x20, 0xb3, 0xe2, 0x6b, 0x54,
	0xbb, 0x66, 0x83, 0xe4, 0x1c, 0x12, 0xff, 0xcb, 0xc8, 0xe3, 0xa9, 0xfb, 0xf8, 0x13, 0x73, 0x32,
	0x91, 0x83, 0x95, 0x72, 0x46, 0x5e, 0x42, 0xec, 0x10, 0xf9, 0x3b, 0xfd, 0xaf, 0x27, 0xaf, 0x20,
	0xf1, 0x63, 0x1d, 0xf6, 0x19, 0x5d, 0xe4, 0x77, 0x90, 0xb2, 0x9c, 0xbd, 0x9b, 0x5d, 0x27, 0x8e,
	0x3f, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x7d, 0x11, 0xa9, 0x10, 0x04, 0x00, 0x00,
}
