query getUser($query: String, $state: Int,  $page: Int, $pageSize: Int) {
  User(query: $query, state: $state, page: $page, pageSize: $pageSize) {
    User {
      id
      groupId
      name
      description
      state
      createdAt
      updatedAt
    }
    page
    pageSize
    total
  }
}

type User {
  id: ID
  name: String
}
