// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line ..\template\index.qtpl:1
package template

//line ..\template\index.qtpl:1
import "github.com/valyala/fasthttp"

//line ..\template\index.qtpl:2
import "fastService/utils"

//line ..\template\index.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ..\template\index.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ..\template\index.qtpl:5
type IndexPage struct {
	CTX *fasthttp.RequestCtx
}

//line ..\template\index.qtpl:11
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line ..\template\index.qtpl:11
	qw422016.N().S(`
	This is the index page
`)
//line ..\template\index.qtpl:13
}

//line ..\template\index.qtpl:13
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line ..\template\index.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line ..\template\index.qtpl:13
	p.StreamTitle(qw422016)
	//line ..\template\index.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line ..\template\index.qtpl:13
}

//line ..\template\index.qtpl:13
func (p *IndexPage) Title() string {
	//line ..\template\index.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line ..\template\index.qtpl:13
	p.WriteTitle(qb422016)
	//line ..\template\index.qtpl:13
	qs422016 := string(qb422016.B)
	//line ..\template\index.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line ..\template\index.qtpl:13
	return qs422016
//line ..\template\index.qtpl:13
}

//line ..\template\index.qtpl:16
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	//line ..\template\index.qtpl:16
	qw422016.N().S(`
	<h1>Index page</h1>
	<div>
		Click links below:
		<ul>
			<li><a href="/moment">瞬间</a></li>
			<li><a href="/chat">聊天</a></li>
		</ul>
	</div>
	<div>
		Some info about you:<br/>
		IP: <b>`)
	//line ..\template\index.qtpl:27
	qw422016.E().S(utils.ToSting(p.CTX.Request.Header.Peek("X-Real-IP")))
	//line ..\template\index.qtpl:27
	qw422016.N().S(`</b><br/>
		User-Agent: <b>`)
	//line ..\template\index.qtpl:28
	qw422016.E().Z(p.CTX.UserAgent())
	//line ..\template\index.qtpl:28
	qw422016.N().S(`</b><br/>
	</div>
`)
//line ..\template\index.qtpl:30
}

//line ..\template\index.qtpl:30
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	//line ..\template\index.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line ..\template\index.qtpl:30
	p.StreamBody(qw422016)
	//line ..\template\index.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line ..\template\index.qtpl:30
}

//line ..\template\index.qtpl:30
func (p *IndexPage) Body() string {
	//line ..\template\index.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
	//line ..\template\index.qtpl:30
	p.WriteBody(qb422016)
	//line ..\template\index.qtpl:30
	qs422016 := string(qb422016.B)
	//line ..\template\index.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
	//line ..\template\index.qtpl:30
	return qs422016
//line ..\template\index.qtpl:30
}
