// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template\index.qtpl:1
package template

//line template\index.qtpl:1
import "github.com/valyala/fasthttp"

//line template\index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template\index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template\index.qtpl:4
type IndexPage struct {
	CTX *fasthttp.RequestCtx
}

//line template\index.qtpl:10
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line template\index.qtpl:10
	qw422016.N().S(`
	This is the index page
`)
//line template\index.qtpl:12
}

//line template\index.qtpl:12
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line template\index.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template\index.qtpl:12
	p.StreamTitle(qw422016)
	//line template\index.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line template\index.qtpl:12
}

//line template\index.qtpl:12
func (p *IndexPage) Title() string {
	//line template\index.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
	//line template\index.qtpl:12
	p.WriteTitle(qb422016)
	//line template\index.qtpl:12
	qs422016 := string(qb422016.B)
	//line template\index.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
	//line template\index.qtpl:12
	return qs422016
//line template\index.qtpl:12
}

//line template\index.qtpl:15
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	//line template\index.qtpl:15
	qw422016.N().S(`
	<h1>Index page</h1>
	<div>
		Click links below:
		<ul>
			<li><a href="/moment">瞬间</a></li>
			<li><a href="/chat">聊天</a></li>
		</ul>
	</div>
	<div>
		Some info about you:<br/>
		IP: <b>`)
	//line template\index.qtpl:26
	qw422016.E().S(p.CTX.RemoteIP().String())
	//line template\index.qtpl:26
	qw422016.N().S(`</b><br/>
		User-Agent: <b>`)
	//line template\index.qtpl:27
	qw422016.E().Z(p.CTX.UserAgent())
	//line template\index.qtpl:27
	qw422016.N().S(`</b><br/>
	</div>
`)
//line template\index.qtpl:29
}

//line template\index.qtpl:29
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	//line template\index.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template\index.qtpl:29
	p.StreamBody(qw422016)
	//line template\index.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line template\index.qtpl:29
}

//line template\index.qtpl:29
func (p *IndexPage) Body() string {
	//line template\index.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
	//line template\index.qtpl:29
	p.WriteBody(qb422016)
	//line template\index.qtpl:29
	qs422016 := string(qb422016.B)
	//line template\index.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
	//line template\index.qtpl:29
	return qs422016
//line template\index.qtpl:29
}
